#!/usr/bin/env python3
"""添加 Hermes Agent 全部斜杠命令（聊天内命令）"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from database.db_manager import DBManager

db = DBManager()
db.init_db()

# 查找 Hermes Agent 分类
ha_cat = None
for root in db.get_categories(parent_id=None):
    if root['name'] == '命令行工具':
        for child in db.get_categories(parent_id=root['id']):
            if child['name'] == 'Hermes Agent':
                ha_cat = child['id']
                break
        break

if not ha_cat:
    print('[ERR] Hermes Agent 分类不存在')
    sys.exit(1)

def add(**kw):
    kw['category_id'] = ha_cat
    kw['os_type'] = '通用'
    db.add_command(**kw)

commands = [
    # ===== Session =====
    {
        'cmd_name': '/new',
        'name_cn': '新建会话',
        'function_desc': '开始一个全新的会话（新的会话ID和历史记录），清除当前对话上下文',
        'syntax': '/new',
        'params_json': '[]',
        'example_basic': '/new',
        'example_adv': '/new  # 清除当前聊天并重新开始',
        'aliases': 'reset,新会话,重置会话',
        'tips': '相当于重新启动一个新会话。当前会话不会丢失，可以通过 resume 恢复。',
    },
    {
        'cmd_name': '/clear',
        'name_cn': '清屏并新建会话',
        'function_desc': '清除终端屏幕并开始一个新的会话',
        'syntax': '/clear',
        'params_json': '[]',
        'example_basic': '/clear',
        'aliases': '清屏,cls,清除屏幕',
        'tips': '仅 CLI 可用。相当于 /new 加上清屏效果。',
    },
    {
        'cmd_name': '/redraw',
        'name_cn': '强制重绘UI',
        'function_desc': '强制重新绘制整个终端UI，适用于终端渲染出现漂移或错乱时恢复显示',
        'syntax': '/redraw',
        'params_json': '[]',
        'example_basic': '/redraw',
        'aliases': '重绘,repaint,刷新界面',
        'tips': '当终端输出出现错位、乱码时使用。仅 CLI 可用。',
    },
    {
        'cmd_name': '/history',
        'name_cn': '显示对话历史',
        'function_desc': '显示当前会话的完整对话历史记录，包括所有用户消息和助手回复',
        'syntax': '/history',
        'params_json': '[]',
        'example_basic': '/history',
        'aliases': '历史,对话历史,历史记录',
        'tips': '仅在 CLI 中可用。会输出完整的对话消息序列。',
    },
    {
        'cmd_name': '/save',
        'name_cn': '保存当前对话',
        'function_desc': '将当前对话保存到文件',
        'syntax': '/save',
        'params_json': '[]',
        'example_basic': '/save',
        'aliases': '保存,存档',
        'tips': '保存到文件后可以离线查看或分享。仅在 CLI 中可用。',
    },
    {
        'cmd_name': '/retry',
        'name_cn': '重试最后一次消息',
        'function_desc': '将最后一次用户消息重新发送给 Agent，获取新的回复',
        'syntax': '/retry',
        'params_json': '[]',
        'example_basic': '/retry',
        'aliases': '重试,重新生成,重发',
        'tips': '当对上一次回复不满意时使用。会重新生成整个回复。',
    },
    {
        'cmd_name': '/undo',
        'name_cn': '撤销上一轮对话',
        'function_desc': '移除最后一条用户消息和对应的助手回复，恢复到上一轮的状态',
        'syntax': '/undo',
        'params_json': '[]',
        'example_basic': '/undo',
        'aliases': '撤销,回退,上一步,撤回',
        'tips': '可以连续使用多次，逐步回退。不会影响之前的会话历史。',
    },
    {
        'cmd_name': '/title',
        'name_cn': '设置会话标题',
        'function_desc': '为当前会话设置一个友好的标题，方便后续查找和恢复',
        'syntax': '/title [name]',
        'params_json': '[{"参数":"name","说明":"会话标题名称，留空则自动生成","必填":"可选"}]',
        'example_basic': '/title 修复登录bug\n/title',
        'aliases': '标题,命名会话,会话标题',
        'tips': '设置有意义的标题方便后续用 /resume 恢复。不传参则自动生成。',
    },
    {
        'cmd_name': '/branch',
        'name_cn': '分支会话',
        'function_desc': '从当前会话分叉出一个新的分支会话，用于探索不同的对话路径（不会丢失当前上下文）',
        'syntax': '/branch [name]',
        'params_json': '[{"参数":"name","说明":"分支名称","必填":"可选"}]',
        'example_basic': '/branch explore-api-v2\n/branch',
        'aliases': 'fork,分支,分叉,探索',
        'tips': '适合"如果换一种方案会怎样"的场景。原会话完整保留。',
    },
    {
        'cmd_name': '/compress',
        'name_cn': '压缩对话上下文',
        'function_desc': '手动压缩对话上下文，将历史消息总结为精炼摘要，减少token消耗',
        'syntax': '/compress [focus topic]',
        'params_json': '[{"参数":"focus topic","说明":"重点关注的话题，压缩时会保留相关上下文","必填":"可选"}]',
        'example_basic': '/compress\n/compress 数据库架构设计',
        'aliases': '压缩,上下文压缩,精简',
        'tips': '当对话很长时使用，可显著降低token消耗。自动压缩策略也在后台运行。',
    },
    {
        'cmd_name': '/rollback',
        'name_cn': '恢复文件系统检查点',
        'function_desc': '列出或恢复文件系统检查点（checkpoints），当启用了 --checkpoints 时，每个破坏性文件操作前都会自动创建快照',
        'syntax': '/rollback [number]',
        'params_json': '[{"参数":"number","说明":"要恢复到的检查点编号，留空则列出所有检查点","必填":"可选"}]',
        'example_basic': '/rollback\n/rollback 3',
        'aliases': '回滚,检查点,checkpoint,快照恢复',
        'tips': '需要在启动时加 --checkpoints 参数。列出检查点后按编号恢复。',
    },
    {
        'cmd_name': '/snapshot',
        'name_cn': '创建/恢复配置快照',
        'function_desc': '创建或恢复 Hermes 配置和状态的快照，支持 create/restore/prune',
        'syntax': '/snapshot [create|restore <id>|prune]',
        'params_json': '[{"参数":"create","说明":"创建当前状态的快照","必填":"可选"},{"参数":"restore <id>","说明":"恢复指定ID的快照","必填":"可选"},{"参数":"prune","说明":"清理旧快照","必填":"可选"}]',
        'example_basic': '/snapshot create\n/snapshot restore abc123',
        'aliases': 'snap,快照,状态快照',
        'tips': '创建配置的快照，可在配置损坏后恢复。仅在 CLI 中可用。',
    },
    {
        'cmd_name': '/stop',
        'name_cn': '终止所有后台进程',
        'function_desc': '杀死所有正在运行的后台进程，包括 /background 启动的任务',
        'syntax': '/stop',
        'params_json': '[]',
        'example_basic': '/stop',
        'aliases': '停止,终止,停,kill',
        'tips': '紧急情况下使用，强制终止所有后台运行的任务。',
    },
    {
        'cmd_name': '/approve',
        'name_cn': '批准危险命令',
        'function_desc': '批准待处理的危险命令执行请求，支持仅本次或永久信任',
        'syntax': '/approve [session|always]',
        'params_json': '[{"参数":"session","说明":"仅本次会话批准","必填":"可选"},{"参数":"always","说明":"永久信任此命令","必填":"可选"}]',
        'example_basic': '/approve\n/approve always',
        'aliases': '批准,同意,许可,确认',
        'tips': '仅在网关（Telegram/Discord/微信）中可用。CLI 模式下直接在终端交互。',
    },
    {
        'cmd_name': '/deny',
        'name_cn': '拒绝危险命令',
        'function_desc': '拒绝待处理的危险命令执行请求',
        'syntax': '/deny',
        'params_json': '[]',
        'example_basic': '/deny',
        'aliases': '拒绝,不同意,取消',
        'tips': '仅在网关中可用。拒绝后命令不会执行。',
    },
    {
        'cmd_name': '/background',
        'name_cn': '在后台运行任务',
        'function_desc': '将提示发送到后台运行，不阻塞当前对话，可以同时处理多个任务',
        'syntax': '/background <prompt>',
        'params_json': '[{"参数":"prompt","说明":"要在后台执行的任务描述","必填":"必填"}]',
        'example_basic': '/background 检查所有日志中的错误\n/background 编译项目并报告结果',
        'aliases': 'bg,btw,后台,后台任务',
        'tips': '后台任务与当前对话并行运行。用 /agents 查看任务进度。适合耗时操作。',
    },
    {
        'cmd_name': '/agents',
        'name_cn': '查看活跃Agent和任务',
        'function_desc': '显示当前所有活跃的 Agent 和正在运行的任务状态',
        'syntax': '/agents',
        'params_json': '[]',
        'example_basic': '/agents',
        'aliases': 'tasks,任务列表,agent列表,活跃任务',
        'tips': '显示每个后台任务的 ID、状态和当前进度。',
    },
    {
        'cmd_name': '/queue',
        'name_cn': '排队发送提示',
        'function_desc': '将提示排入队列，等待当前轮次完成后自动执行（不中断当前操作）',
        'syntax': '/queue <prompt>',
        'params_json': '[{"参数":"prompt","说明":"要排队的提示","必填":"必填"}]',
        'example_basic': '/queue 完成后告诉我结果\n/q 检查代码格式',
        'aliases': 'q,排队,队列',
        'tips': '和 /background 不同，/queue 在当前轮结束后执行，不创建独立任务。',
    },
    {
        'cmd_name': '/steer',
        'name_cn': '注入方向指引',
        'function_desc': '在下一次工具调用完成后插入一条指引消息，不中断当前正在执行的工具操作',
        'syntax': '/steer <prompt>',
        'params_json': '[{"参数":"prompt","说明":"指引内容","必填":"必填"}]',
        'example_basic': '/steer 注意看日志中的具体错误行\n/steer 改用JSON格式输出',
        'aliases': '指引,导向,中途修正',
        'tips': '在 Agent 正在执行多步操作时注入中间指令，避免打断流程。',
    },
    {
        'cmd_name': '/status',
        'name_cn': '查看会话信息',
        'function_desc': '显示当前会话的基本信息，包括会话ID、模型、使用量等',
        'syntax': '/status',
        'params_json': '[]',
        'example_basic': '/status',
        'aliases': '状态,会话状态,信息',
        'tips': '快速了解当前会话的基本参数和使用情况。',
    },
    {
        'cmd_name': '/profile',
        'name_cn': '显示配置文件',
        'function_desc': '显示当前活跃的配置文件名称和 Hermes 主目录路径',
        'syntax': '/profile',
        'params_json': '[]',
        'example_basic': '/profile',
        'aliases': '配置文件,当前配置',
        'tips': '当使用多 profile 时，快速确认当前正在使用的是哪个。',
    },
    {
        'cmd_name': '/sethome',
        'name_cn': '设置主页频道',
        'function_desc': '将当前聊天设置为网关消息的主页频道（home channel），所有非定向消息会投递到这里',
        'syntax': '/sethome',
        'params_json': '[]',
        'example_basic': '/sethome',
        'aliases': 'set-home,设置主页,设为首页',
        'tips': '仅在网关中可用。定时任务的结果、系统通知默认投递到主页频道。',
    },
    {
        'cmd_name': '/resume',
        'name_cn': '恢复之前的会话',
        'function_desc': '通过名称恢复之前命名过的会话，不传参则恢复最近的一个会话',
        'syntax': '/resume [name]',
        'params_json': '[{"参数":"name","说明":"要恢复的会话名称，留空恢复最近一个","必填":"可选"}]',
        'example_basic': '/resume\n/resume 修复登录bug',
        'aliases': '恢复,继续,resume',
        'tips': '会话需要先通过 /title 命名才能通过名称恢复。不传参会自动恢复最近对话。',
    },

    # ===== Configuration =====
    {
        'cmd_name': '/config',
        'name_cn': '查看当前配置',
        'function_desc': '显示当前 Hermes Agent 的配置信息',
        'syntax': '/config',
        'params_json': '[]',
        'example_basic': '/config',
        'aliases': '配置,查看配置',
        'tips': '仅在 CLI 中可用。会输出当前加载的完整配置。',
    },
    {
        'cmd_name': '/model',
        'name_cn': '切换模型',
        'function_desc': '临时切换当前会话使用的推理模型和提供商，支持 --global 持久化',
        'syntax': '/model [model] [--provider name] [--global]',
        'params_json': '[{"参数":"model","说明":"模型名，如 claude-sonnet-4 / gpt-4o","必填":"可选"},{"参数":"--provider name","说明":"指定提供商","必填":"可选"},{"参数":"--global","说明":"设为全局默认（持久化到配置）","必填":"可选"}]',
        'example_basic': '/model claude-sonnet-4\n/model --provider anthropic\n/model gpt-4o --global',
        'aliases': 'provider,切换模型,模型切换,换模型',
        'tips': '不传参数进入交互式选择。不加 --global 仅当前会话有效。',
    },
    {
        'cmd_name': '/gquota',
        'name_cn': '查看Gemini配额',
        'function_desc': '显示 Google Gemini Code Assist 的 API 配额使用情况',
        'syntax': '/gquota',
        'params_json': '[]',
        'example_basic': '/gquota',
        'aliases': 'gemini配额,配额查询,google配额',
        'tips': '仅在使用 Gemini 提供商时有效。仅在 CLI 中可用。',
    },
    {
        'cmd_name': '/personality',
        'name_cn': '设置人格模式',
        'function_desc': '设置预定义的人格模式，改变 Agent 的回复风格和语气',
        'syntax': '/personality [name]',
        'params_json': '[{"参数":"name","说明":"人格名称，不传则查看当前人格","必填":"可选"}]',
        'example_basic': '/personality\n/personality pirate\n/personality default',
        'aliases': '人格,性格,风格,角色扮演',
        'tips': '不传参查看当前人格。不同人格会影响回复的语气和方式。',
    },
    {
        'cmd_name': '/statusbar',
        'name_cn': '切换状态栏',
        'function_desc': '切换是否显示上下文/模型状态栏',
        'syntax': '/statusbar',
        'params_json': '[]',
        'example_basic': '/statusbar',
        'aliases': 'sb,状态栏,显示状态栏',
        'tips': '仅在 CLI 中可用。切换底部状态栏的显示/隐藏。',
    },
    {
        'cmd_name': '/verbose',
        'name_cn': '切换工具输出级别',
        'function_desc': '循环切换工具进度显示的详细程度：关闭 → 精简 → 全部 → 详细',
        'syntax': '/verbose',
        'params_json': '[]',
        'example_basic': '/verbose',
        'aliases': '详细输出,日志级别,工具显示',
        'tips': '循环模式。频繁按 /verbose 切换不同级别直到满意。',
    },
    {
        'cmd_name': '/footer',
        'name_cn': '开关回复脚注',
        'function_desc': '切换是否在网关消息的末尾显示运行时间、token消耗等元数据脚注',
        'syntax': '/footer [on|off|status]',
        'params_json': '[{"参数":"on","说明":"开启脚注","必填":"可选"},{"参数":"off","说明":"关闭脚注","必填":"可选"},{"参数":"status","说明":"查看当前状态","必填":"可选"}]',
        'example_basic': '/footer on\n/footer off\n/footer status',
        'aliases': '脚注,元数据,显示脚注',
        'tips': '默认关闭。开启后每条回复末尾会显示模型、耗时、token等信息。',
    },
    {
        'cmd_name': '/yolo',
        'name_cn': '切换无审批模式',
        'function_desc': '切换 YOLO 模式，开启后跳过所有危险命令的确认审批，直接执行',
        'syntax': '/yolo',
        'params_json': '[]',
        'example_basic': '/yolo',
        'aliases': 'yolo,冒险模式,跳过确认,无审批',
        'tips': '⚠️ 谨慎使用！开启后 Agent 可以不经确认直接执行危险命令。建议临时使用后关闭。',
    },
    {
        'cmd_name': '/reasoning',
        'name_cn': '管理推理设置',
        'function_desc': '管理推理（reasoning）的详细程度和显示方式，支持设置级别和显示控制',
        'syntax': '/reasoning [level|show|hide|on|off]',
        'params_json': '[{"参数":"none","说明":"关闭推理","必填":"可选"},{"参数":"minimal/low/medium/high/xhigh","说明":"设置推理详细程度","必填":"可选"},{"参数":"show/hide","说明":"显示/隐藏推理内容","必填":"可选"},{"参数":"on/off","说明":"开启/关闭推理","必填":"可选"}]',
        'example_basic': '/reasoning high\n/reasoning hide\n/reasoning off',
        'aliases': '推理,思维链,reasoning,思考过程',
        'tips': '不同模型支持的推理级别不同。xhigh 可能显著增加响应时间。',
    },
    {
        'cmd_name': '/fast',
        'name_cn': '切换快速模式',
        'function_desc': '切换快速模式——OpenAI Priority Processing / Anthropic Fast Mode',
        'syntax': '/fast [normal|fast|status|on|off]',
        'params_json': '[{"参数":"normal","说明":"正常模式（标准处理）","必填":"可选"},{"参数":"fast","说明":"快速模式（优先级处理）","必填":"可选"},{"参数":"status","说明":"查看当前模式","必填":"可选"}]',
        'example_basic': '/fast\n/fast fast\n/fast status',
        'aliases': '快速模式,fast,速度模式',
        'tips': '快速模式可能影响回复质量。在某些提供商中需要额外付费。',
    },
    {
        'cmd_name': '/skin',
        'name_cn': '切换显示主题',
        'function_desc': '查看或更改终端显示皮肤/主题',
        'syntax': '/skin [name]',
        'params_json': '[{"参数":"name","说明":"主题名称，不传则查看当前主题","必填":"可选"}]',
        'example_basic': '/skin\n/skin dark\n/skin light',
        'aliases': '主题,皮肤,换肤,theme',
        'tips': '仅在 CLI 中可用。不同皮肤改变终端颜色方案。',
    },
    {
        'cmd_name': '/indicator',
        'name_cn': '选择忙碌指示器',
        'function_desc': '选择 TUI 忙碌指示器的风格（kaomoji/emoji/unicode/ascii）',
        'syntax': '/indicator [kaomoji|emoji|unicode|ascii]',
        'params_json': '[{"参数":"kaomoji","说明":"颜文字风格 (^_^)","必填":"可选"},{"参数":"emoji","说明":"Emoji风格 😊","必填":"可选"},{"参数":"unicode","说明":"Unicode字符","必填":"可选"},{"参数":"ascii","说明":"纯ASCII","必填":"可选"}]',
        'example_basic': '/indicator kaomoji\n/indicator emoji',
        'aliases': '指示器,忙碌动画,加载动画',
        'tips': '不同风格适合不同的终端环境。ASCII 兼容性最好。',
    },
    {
        'cmd_name': '/voice',
        'name_cn': '切换语音模式',
        'function_desc': '切换语音输入/输出模式，支持 TTS（文字转语音）',
        'syntax': '/voice [on|off|tts|status]',
        'params_json': '[{"参数":"on","说明":"开启语音模式","必填":"可选"},{"参数":"off","说明":"关闭语音模式","必填":"可选"},{"参数":"tts","说明":"单独切换TTS","必填":"可选"},{"参数":"status","说明":"查看当前状态","必填":"可选"}]',
        'example_basic': '/voice\n/voice on\n/voice status',
        'aliases': '语音,声音,tts,语音模式',
        'tips': '需要配置 TTS provider 才能使用语音输出。',
    },
    {
        'cmd_name': '/busy',
        'name_cn': '设置忙碌时Enter行为',
        'function_desc': '控制在 Agent 正在工作时按 Enter 键的行为（排队/指引/中断/查看状态）',
        'syntax': '/busy [queue|steer|interrupt|status]',
        'params_json': '[{"参数":"queue","说明":"排队等待（默认）","必填":"可选"},{"参数":"steer","说明":"发送当前输入作为指引","必填":"可选"},{"参数":"interrupt","说明":"中断当前操作","必填":"可选"},{"参数":"status","说明":"查看当前模式","必填":"可选"}]',
        'example_basic': '/busy steer\n/busy queue\n/busy status',
        'aliases': '忙碌行为,enter行为,打断设置',
        'tips': '仅在 CLI 中可用。根据自己的使用习惯选择合适的模式。',
    },

    # ===== Tools & Skills =====
    {
        'cmd_name': '/tools',
        'name_cn': '管理工具',
        'function_desc': '管理工具的启用状态：列出所有工具、禁用或启用指定的工具集或MCP工具',
        'syntax': '/tools [list|disable|enable] [name...]',
        'params_json': '[{"参数":"list","说明":"列出所有工具及状态","必填":"可选"},{"参数":"disable name","说明":"禁用指定工具","必填":"可选"},{"参数":"enable name","说明":"启用指定工具","必填":"可选"}]',
        'example_basic': '/tools\n/tools list\n/tools disable web',
        'aliases': '工具,管理工具,tool管理',
        'tips': '仅在 CLI 中可用。内置工具用名称（如 web/memory），MCP工具用 server:tool 格式。',
    },
    {
        'cmd_name': '/toolsets',
        'name_cn': '列出可用工具集',
        'function_desc': '列出当前所有可用的工具集（toolsets）',
        'syntax': '/toolsets',
        'params_json': '[]',
        'example_basic': '/toolsets',
        'aliases': '工具集,可用工具',
        'tips': '仅在 CLI 中可用。显示可启用的所有工具集名称。',
    },
    {
        'cmd_name': '/skills',
        'name_cn': '管理技能',
        'function_desc': '搜索、浏览、预览或安装技能',
        'syntax': '/skills [search|browse|inspect|install] [name]',
        'params_json': '[{"参数":"search","说明":"搜索技能","必填":"可选"},{"参数":"browse","说明":"浏览所有技能","必填":"可选"},{"参数":"inspect name","说明":"预览技能内容","必填":"可选"},{"参数":"install name","说明":"安装技能","必填":"可选"}]',
        'example_basic': '/skills search github\n/skills browse\n/skills inspect github-auth\n/skills install github-auth',
        'aliases': '技能,skills,skill管理',
        'tips': '仅在 CLI 中可用。技能从 skills.sh 等注册中心获取。',
    },
    {
        'cmd_name': '/cron',
        'name_cn': '管理定时任务',
        'function_desc': '管理定时调度任务的管理命令：列出/添加/编辑/暂停/恢复/运行/删除',
        'syntax': '/cron [subcommand]',
        'params_json': '[{"参数":"list","说明":"列出定时任务","必填":"可选"},{"参数":"add/create","说明":"添加定时任务","必填":"可选"},{"参数":"edit","说明":"编辑任务","必填":"可选"},{"参数":"pause","说明":"暂停任务","必填":"可选"},{"参数":"resume","说明":"恢复任务","必填":"可选"},{"参数":"run","说明":"立即执行任务","必填":"可选"},{"参数":"remove","说明":"删除任务","必填":"可选"}]',
        'example_basic': '/cron list\n/cron add\n/cron remove job_abc123',
        'aliases': '定时任务,调度,cron管理',
        'tips': '仅在 CLI 中可用。定时任务在独立会话中运行，提示词需自包含。',
    },
    {
        'cmd_name': '/curator',
        'name_cn': '后台技能维护',
        'function_desc': '后台技能的维护管理：查看状态、运行、暂停、固定、归档',
        'syntax': '/curator [status|run|pause|resume|pin|unpin|restore]',
        'params_json': '[{"参数":"status","说明":"查看技能状态","必填":"可选"},{"参数":"run","说明":"立即运行","必填":"可选"},{"参数":"pause/resume","说明":"暂停/恢复","必填":"可选"},{"参数":"pin/unpin","说明":"固定/取消固定","必填":"可选"},{"参数":"restore","说明":"恢复技能","必填":"可选"}]',
        'example_basic': '/curator status\n/curator run\n/curator pin',
        'aliases': 'curator,技能维护,后台维护',
        'tips': '后台技能可以定时自动运行，如代码清理、数据备份等。',
    },
    {
        'cmd_name': '/reload',
        'name_cn': '重新加载环境变量',
        'function_desc': '重新加载 ~/.hermes/.env 中的环境变量到当前运行会话',
        'syntax': '/reload',
        'params_json': '[]',
        'example_basic': '/reload',
        'aliases': '重载,重新加载,reload env,env重载',
        'tips': '修改 .env 文件后需要执行此命令让变更生效。仅在 CLI 中可用。',
    },
    {
        'cmd_name': '/reload-mcp',
        'name_cn': '重新加载MCP服务器',
        'function_desc': '从配置文件重新加载 MCP 服务器连接',
        'syntax': '/reload-mcp',
        'params_json': '[]',
        'example_basic': '/reload-mcp',
        'aliases': 'reload_mcp,刷新mcp,mcp重载',
        'tips': '添加/修改 MCP 服务器配置后执行。无需重启整个 Hermes。',
    },
    {
        'cmd_name': '/reload-skills',
        'name_cn': '重新扫描技能',
        'function_desc': '重新扫描 ~/.hermes/skills/ 目录，发现新安装或移除的技能',
        'syntax': '/reload-skills',
        'params_json': '[]',
        'example_basic': '/reload-skills',
        'aliases': 'reload_skills,刷新技能,扫描技能',
        'tips': '手动安装技能到 skills 目录后执行。无需重启会话。',
    },
    {
        'cmd_name': '/browser',
        'name_cn': '连接浏览器',
        'function_desc': '通过 Chrome DevTools Protocol (CDP) 将浏览器工具连接到本地 Chrome',
        'syntax': '/browser [connect|disconnect|status]',
        'params_json': '[{"参数":"connect","说明":"连接到Chrome","必填":"可选"},{"参数":"disconnect","说明":"断开连接","必填":"可选"},{"参数":"status","说明":"查看连接状态","必填":"可选"}]',
        'example_basic': '/browser status\n/browser connect',
        'aliases': '浏览器,chrome,cdp,浏览器工具',
        'tips': '需要先启动 Chrome 并开启远程调试端口（--remote-debugging-port=9222）。',
    },
    {
        'cmd_name': '/plugins',
        'name_cn': '列出已安装插件',
        'function_desc': '列出所有已安装的插件及其状态',
        'syntax': '/plugins',
        'params_json': '[]',
        'example_basic': '/plugins',
        'aliases': '插件,插件列表,已安装插件',
        'tips': '仅列出已安装的插件。需要在 CLI 中用 hermes plugins install 安装。',
    },

    # ===== Info =====
    {
        'cmd_name': '/commands',
        'name_cn': '浏览所有命令',
        'function_desc': '分页浏览所有可用的斜杠命令和技能命令',
        'syntax': '/commands [page]',
        'params_json': '[{"参数":"page","说明":"页码，从1开始","必填":"可选"}]',
        'example_basic': '/commands\n/commands 2',
        'aliases': '命令列表,所有命令,cmds',
        'tips': '仅在网关中可用。分页显示，每页显示一定数量的命令。',
    },
    {
        'cmd_name': '/help',
        'name_cn': '显示帮助信息',
        'function_desc': '显示所有可用命令及其简短描述',
        'syntax': '/help',
        'params_json': '[]',
        'example_basic': '/help',
        'aliases': '帮助,?,h,帮助信息',
        'tips': '快速概览所有可用命令。按分类组织显示。',
    },
    {
        'cmd_name': '/restart',
        'name_cn': '优雅重启网关',
        'function_desc': '在执行中的任务完成后优雅地重启网关服务',
        'syntax': '/restart',
        'params_json': '[]',
        'example_basic': '/restart',
        'aliases': '重启,重启动,restart gateway',
        'tips': '仅在网关中可用。会等待当前正在运行的任务完成后再重启。',
    },
    {
        'cmd_name': '/usage',
        'name_cn': '查看Token用量',
        'function_desc': '显示当前会话的 token 使用量和速率限制信息',
        'syntax': '/usage',
        'params_json': '[]',
        'example_basic': '/usage',
        'aliases': '用量,token,使用统计',
        'tips': '显示当前会话已消耗的 token 数量和速率限制。',
    },
    {
        'cmd_name': '/insights',
        'name_cn': '查看使用分析',
        'function_desc': '显示使用统计和趋势分析，支持指定分析天数',
        'syntax': '/insights [days]',
        'params_json': '[{"参数":"days","说明":"分析的天数范围，默认30天","必填":"可选"}]',
        'example_basic': '/insights\n/insights 7',
        'aliases': '分析,统计,数据分析,insights',
        'tips': '显示会话数量、token消耗趋势、常用工具等。',
    },
    {
        'cmd_name': '/platforms',
        'name_cn': '查看网关平台状态',
        'function_desc': '显示网关/消息平台的运行状态',
        'syntax': '/platforms',
        'params_json': '[]',
        'example_basic': '/platforms',
        'aliases': 'gateway,平台状态,网关状态',
        'tips': '仅在 CLI 中可用。显示各消息平台的连接状态。',
    },
    {
        'cmd_name': '/copy',
        'name_cn': '复制最后回复',
        'function_desc': '将最后一条助手的回复内容复制到系统剪贴板',
        'syntax': '/copy [number]',
        'params_json': '[{"参数":"number","说明":"要复制的代码块序号，留空复制全部","必填":"可选"}]',
        'example_basic': '/copy\n/copy 2',
        'aliases': '复制,拷贝,clipboard',
        'tips': '仅在 CLI 中可用。可指定复制第几个代码块。',
    },
    {
        'cmd_name': '/paste',
        'name_cn': '粘贴剪贴板图片',
        'function_desc': '将当前系统剪贴板中的图片附加到下一次提示中',
        'syntax': '/paste',
        'params_json': '[]',
        'example_basic': '/paste',
        'aliases': '粘贴,clipboard image,图片粘贴',
        'tips': '仅在 CLI 中可用。用于直接粘贴截图进行分析。',
    },
    {
        'cmd_name': '/image',
        'name_cn': '附加本地图片',
        'function_desc': '附加一个本地图片文件到下一次提示中',
        'syntax': '/image <path>',
        'params_json': '[{"参数":"path","说明":"图片文件路径","必填":"必填"}]',
        'example_basic': '/image screenshot.png\n/image /path/to/photo.jpg',
        'aliases': '图片,附加图片,上传图片',
        'tips': '仅在 CLI 中可用。支持 jpg/png/gif/webp 等常见格式。',
    },
    {
        'cmd_name': '/update',
        'name_cn': '更新 Hermes Agent',
        'function_desc': '将 Hermes Agent 更新到最新版本（仅网关中可用）',
        'syntax': '/update',
        'params_json': '[]',
        'example_basic': '/update',
        'aliases': '更新,升级,update',
        'tips': '仅在网关中可用。CLI 中用 hermes update。',
    },
    {
        'cmd_name': '/debug',
        'name_cn': '上传调试报告',
        'function_desc': '上传调试报告（系统信息+日志），获取可分享的链接',
        'syntax': '/debug',
        'params_json': '[]',
        'example_basic': '/debug',
        'aliases': '调试,debug,诊断报告,错误报告',
        'tips': '向技术支持求助时运行此命令，生成包含诊断信息的分享链接。',
    },

    # ===== Exit =====
    {
        'cmd_name': '/quit',
        'name_cn': '退出CLI',
        'function_desc': '退出 Hermes Agent 命令行界面',
        'syntax': '/quit',
        'params_json': '[]',
        'example_basic': '/quit',
        'aliases': 'exit,退出,关闭,退出CLI',
        'tips': '仅在 CLI 中可用。网关中请使用 /restart。',
    },
]

for cmd in commands:
    add(**cmd)

total = db.conn.execute("SELECT COUNT(*) FROM commands WHERE category_id=?", (ha_cat,)).fetchone()[0]
grand = db.get_total_count()
print(f'[OK] Hermes Agent 分类（含斜杠命令）: {total} 条')
print(f'[OK] 数据库总计: {grand}')
